from .usuario_form import Usuario_Form
from .nueva_contraseña_form import Nueva_Contraseña_Form
from .recuperar_contraseña_form import RecuperarContraseñaForm
from .alumno_form import AlumnoForm
from .asignatura_form import AsignaturaForm
from .documentacion_alumno_form import DocumentacionAlumnoForm
